//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace Arachnode.Test.CrawlerServiceReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CrawlerServiceSoap", Namespace="http://arachnode.net/CrawlerService")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ABehaviorOfArachnodeDAO))]
    public partial class CrawlerService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConstructorOperationCompleted;
        
        private System.Threading.SendOrPostCallback DestructorOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetApplicationSettingsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetWebSettingsOperationCompleted;
        
        private System.Threading.SendOrPostCallback CrawlOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCrawlActionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCrawlRulesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEngineActionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback StartEngineOperationCompleted;
        
        private System.Threading.SendOrPostCallback StopEngineOperationCompleted;
        
        private System.Threading.SendOrPostCallback PauseEngineOperationCompleted;
        
        private System.Threading.SendOrPostCallback ResumeEngineOperationCompleted;
        
        private System.Threading.SendOrPostCallback ResetOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetApplicationSettingsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetWebSettingsOperationCompleted;
        
        private System.Threading.SendOrPostCallback InitializeConfigurationOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPerformanceCountersForArachnodeDotNetOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPerformanceCountersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllTableRowCountsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CrawlerService() {
            this.Url = global::Arachnode.Test.Properties.Settings.Default.Arachnode_Test_CrawlerServiceReference_CrawlerService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConstructorCompletedEventHandler ConstructorCompleted;
        
        /// <remarks/>
        public event DestructorCompletedEventHandler DestructorCompleted;
        
        /// <remarks/>
        public event SetApplicationSettingsCompletedEventHandler SetApplicationSettingsCompleted;
        
        /// <remarks/>
        public event SetWebSettingsCompletedEventHandler SetWebSettingsCompleted;
        
        /// <remarks/>
        public event CrawlCompletedEventHandler CrawlCompleted;
        
        /// <remarks/>
        public event GetCrawlActionsCompletedEventHandler GetCrawlActionsCompleted;
        
        /// <remarks/>
        public event GetCrawlRulesCompletedEventHandler GetCrawlRulesCompleted;
        
        /// <remarks/>
        public event GetEngineActionsCompletedEventHandler GetEngineActionsCompleted;
        
        /// <remarks/>
        public event StartEngineCompletedEventHandler StartEngineCompleted;
        
        /// <remarks/>
        public event StopEngineCompletedEventHandler StopEngineCompleted;
        
        /// <remarks/>
        public event PauseEngineCompletedEventHandler PauseEngineCompleted;
        
        /// <remarks/>
        public event ResumeEngineCompletedEventHandler ResumeEngineCompleted;
        
        /// <remarks/>
        public event ResetCompletedEventHandler ResetCompleted;
        
        /// <remarks/>
        public event GetApplicationSettingsCompletedEventHandler GetApplicationSettingsCompleted;
        
        /// <remarks/>
        public event GetWebSettingsCompletedEventHandler GetWebSettingsCompleted;
        
        /// <remarks/>
        public event InitializeConfigurationCompletedEventHandler InitializeConfigurationCompleted;
        
        /// <remarks/>
        public event GetPerformanceCountersForArachnodeDotNetCompletedEventHandler GetPerformanceCountersForArachnodeDotNetCompleted;
        
        /// <remarks/>
        public event GetPerformanceCountersCompletedEventHandler GetPerformanceCountersCompleted;
        
        /// <remarks/>
        public event GetAllTableRowCountsCompletedEventHandler GetAllTableRowCountsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://arachnode.net/CrawlerService/Constructor", RequestNamespace="http://arachnode.net/CrawlerService", ResponseNamespace="http://arachnode.net/CrawlerService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Constructor(ApplicationSettings applicationSettings, WebSettings webSettings, CrawlMode crawlMode, bool enableRenderers) {
            this.Invoke("Constructor", new object[] {
                        applicationSettings,
                        webSettings,
                        crawlMode,
                        enableRenderers});
        }
        
        /// <remarks/>
        public void ConstructorAsync(ApplicationSettings applicationSettings, WebSettings webSettings, CrawlMode crawlMode, bool enableRenderers) {
            this.ConstructorAsync(applicationSettings, webSettings, crawlMode, enableRenderers, null);
        }
        
        /// <remarks/>
        public void ConstructorAsync(ApplicationSettings applicationSettings, WebSettings webSettings, CrawlMode crawlMode, bool enableRenderers, object userState) {
            if ((this.ConstructorOperationCompleted == null)) {
                this.ConstructorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConstructorOperationCompleted);
            }
            this.InvokeAsync("Constructor", new object[] {
                        applicationSettings,
                        webSettings,
                        crawlMode,
                        enableRenderers}, this.ConstructorOperationCompleted, userState);
        }
        
        private void OnConstructorOperationCompleted(object arg) {
            if ((this.ConstructorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConstructorCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://arachnode.net/CrawlerService/Destructor", RequestNamespace="http://arachnode.net/CrawlerService", ResponseNamespace="http://arachnode.net/CrawlerService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Destructor() {
            this.Invoke("Destructor", new object[0]);
        }
        
        /// <remarks/>
        public void DestructorAsync() {
            this.DestructorAsync(null);
        }
        
        /// <remarks/>
        public void DestructorAsync(object userState) {
            if ((this.DestructorOperationCompleted == null)) {
                this.DestructorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDestructorOperationCompleted);
            }
            this.InvokeAsync("Destructor", new object[0], this.DestructorOperationCompleted, userState);
        }
        
        private void OnDestructorOperationCompleted(object arg) {
            if ((this.DestructorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DestructorCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://arachnode.net/CrawlerService/SetApplicationSettings", RequestNamespace="http://arachnode.net/CrawlerService", ResponseNamespace="http://arachnode.net/CrawlerService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetApplicationSettings(ApplicationSettings applicationSettings) {
            this.Invoke("SetApplicationSettings", new object[] {
                        applicationSettings});
        }
        
        /// <remarks/>
        public void SetApplicationSettingsAsync(ApplicationSettings applicationSettings) {
            this.SetApplicationSettingsAsync(applicationSettings, null);
        }
        
        /// <remarks/>
        public void SetApplicationSettingsAsync(ApplicationSettings applicationSettings, object userState) {
            if ((this.SetApplicationSettingsOperationCompleted == null)) {
                this.SetApplicationSettingsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetApplicationSettingsOperationCompleted);
            }
            this.InvokeAsync("SetApplicationSettings", new object[] {
                        applicationSettings}, this.SetApplicationSettingsOperationCompleted, userState);
        }
        
        private void OnSetApplicationSettingsOperationCompleted(object arg) {
            if ((this.SetApplicationSettingsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetApplicationSettingsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://arachnode.net/CrawlerService/SetWebSettings", RequestNamespace="http://arachnode.net/CrawlerService", ResponseNamespace="http://arachnode.net/CrawlerService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetWebSettings(WebSettings webSettings) {
            this.Invoke("SetWebSettings", new object[] {
                        webSettings});
        }
        
        /// <remarks/>
        public void SetWebSettingsAsync(WebSettings webSettings) {
            this.SetWebSettingsAsync(webSettings, null);
        }
        
        /// <remarks/>
        public void SetWebSettingsAsync(WebSettings webSettings, object userState) {
            if ((this.SetWebSettingsOperationCompleted == null)) {
                this.SetWebSettingsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetWebSettingsOperationCompleted);
            }
            this.InvokeAsync("SetWebSettings", new object[] {
                        webSettings}, this.SetWebSettingsOperationCompleted, userState);
        }
        
        private void OnSetWebSettingsOperationCompleted(object arg) {
            if ((this.SetWebSettingsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetWebSettingsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://arachnode.net/CrawlerService/Crawl", RequestNamespace="http://arachnode.net/CrawlerService", ResponseNamespace="http://arachnode.net/CrawlerService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Crawl(string absoluteUri, int depth, UriClassificationType restrictCrawlTo, UriClassificationType restrictDiscoveriesTo, double priority, RenderType renderType, RenderType renderTypeForChildren) {
            object[] results = this.Invoke("Crawl", new object[] {
                        absoluteUri,
                        depth,
                        restrictCrawlTo,
                        restrictDiscoveriesTo,
                        priority,
                        renderType,
                        renderTypeForChildren});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CrawlAsync(string absoluteUri, int depth, UriClassificationType restrictCrawlTo, UriClassificationType restrictDiscoveriesTo, double priority, RenderType renderType, RenderType renderTypeForChildren) {
            this.CrawlAsync(absoluteUri, depth, restrictCrawlTo, restrictDiscoveriesTo, priority, renderType, renderTypeForChildren, null);
        }
        
        /// <remarks/>
        public void CrawlAsync(string absoluteUri, int depth, UriClassificationType restrictCrawlTo, UriClassificationType restrictDiscoveriesTo, double priority, RenderType renderType, RenderType renderTypeForChildren, object userState) {
            if ((this.CrawlOperationCompleted == null)) {
                this.CrawlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCrawlOperationCompleted);
            }
            this.InvokeAsync("Crawl", new object[] {
                        absoluteUri,
                        depth,
                        restrictCrawlTo,
                        restrictDiscoveriesTo,
                        priority,
                        renderType,
                        renderTypeForChildren}, this.CrawlOperationCompleted, userState);
        }
        
        private void OnCrawlOperationCompleted(object arg) {
            if ((this.CrawlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CrawlCompleted(this, new CrawlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://arachnode.net/CrawlerService/GetCrawlActions", RequestNamespace="http://arachnode.net/CrawlerService", ResponseNamespace="http://arachnode.net/CrawlerService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ACrawlActionOfArachnodeDAO[] GetCrawlActions() {
            object[] results = this.Invoke("GetCrawlActions", new object[0]);
            return ((ACrawlActionOfArachnodeDAO[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCrawlActionsAsync() {
            this.GetCrawlActionsAsync(null);
        }
        
        /// <remarks/>
        public void GetCrawlActionsAsync(object userState) {
            if ((this.GetCrawlActionsOperationCompleted == null)) {
                this.GetCrawlActionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCrawlActionsOperationCompleted);
            }
            this.InvokeAsync("GetCrawlActions", new object[0], this.GetCrawlActionsOperationCompleted, userState);
        }
        
        private void OnGetCrawlActionsOperationCompleted(object arg) {
            if ((this.GetCrawlActionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCrawlActionsCompleted(this, new GetCrawlActionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://arachnode.net/CrawlerService/GetCrawlRules", RequestNamespace="http://arachnode.net/CrawlerService", ResponseNamespace="http://arachnode.net/CrawlerService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ACrawlRuleOfArachnodeDAO[] GetCrawlRules() {
            object[] results = this.Invoke("GetCrawlRules", new object[0]);
            return ((ACrawlRuleOfArachnodeDAO[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCrawlRulesAsync() {
            this.GetCrawlRulesAsync(null);
        }
        
        /// <remarks/>
        public void GetCrawlRulesAsync(object userState) {
            if ((this.GetCrawlRulesOperationCompleted == null)) {
                this.GetCrawlRulesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCrawlRulesOperationCompleted);
            }
            this.InvokeAsync("GetCrawlRules", new object[0], this.GetCrawlRulesOperationCompleted, userState);
        }
        
        private void OnGetCrawlRulesOperationCompleted(object arg) {
            if ((this.GetCrawlRulesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCrawlRulesCompleted(this, new GetCrawlRulesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://arachnode.net/CrawlerService/GetEngineActions", RequestNamespace="http://arachnode.net/CrawlerService", ResponseNamespace="http://arachnode.net/CrawlerService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AEngineActionOfArachnodeDAO[] GetEngineActions() {
            object[] results = this.Invoke("GetEngineActions", new object[0]);
            return ((AEngineActionOfArachnodeDAO[])(results[0]));
        }
        
        /// <remarks/>
        public void GetEngineActionsAsync() {
            this.GetEngineActionsAsync(null);
        }
        
        /// <remarks/>
        public void GetEngineActionsAsync(object userState) {
            if ((this.GetEngineActionsOperationCompleted == null)) {
                this.GetEngineActionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEngineActionsOperationCompleted);
            }
            this.InvokeAsync("GetEngineActions", new object[0], this.GetEngineActionsOperationCompleted, userState);
        }
        
        private void OnGetEngineActionsOperationCompleted(object arg) {
            if ((this.GetEngineActionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEngineActionsCompleted(this, new GetEngineActionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://arachnode.net/CrawlerService/StartEngine", RequestNamespace="http://arachnode.net/CrawlerService", ResponseNamespace="http://arachnode.net/CrawlerService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void StartEngine() {
            this.Invoke("StartEngine", new object[0]);
        }
        
        /// <remarks/>
        public void StartEngineAsync() {
            this.StartEngineAsync(null);
        }
        
        /// <remarks/>
        public void StartEngineAsync(object userState) {
            if ((this.StartEngineOperationCompleted == null)) {
                this.StartEngineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStartEngineOperationCompleted);
            }
            this.InvokeAsync("StartEngine", new object[0], this.StartEngineOperationCompleted, userState);
        }
        
        private void OnStartEngineOperationCompleted(object arg) {
            if ((this.StartEngineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StartEngineCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://arachnode.net/CrawlerService/StopEngine", RequestNamespace="http://arachnode.net/CrawlerService", ResponseNamespace="http://arachnode.net/CrawlerService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void StopEngine() {
            this.Invoke("StopEngine", new object[0]);
        }
        
        /// <remarks/>
        public void StopEngineAsync() {
            this.StopEngineAsync(null);
        }
        
        /// <remarks/>
        public void StopEngineAsync(object userState) {
            if ((this.StopEngineOperationCompleted == null)) {
                this.StopEngineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStopEngineOperationCompleted);
            }
            this.InvokeAsync("StopEngine", new object[0], this.StopEngineOperationCompleted, userState);
        }
        
        private void OnStopEngineOperationCompleted(object arg) {
            if ((this.StopEngineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StopEngineCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://arachnode.net/CrawlerService/PauseEngine", RequestNamespace="http://arachnode.net/CrawlerService", ResponseNamespace="http://arachnode.net/CrawlerService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void PauseEngine() {
            this.Invoke("PauseEngine", new object[0]);
        }
        
        /// <remarks/>
        public void PauseEngineAsync() {
            this.PauseEngineAsync(null);
        }
        
        /// <remarks/>
        public void PauseEngineAsync(object userState) {
            if ((this.PauseEngineOperationCompleted == null)) {
                this.PauseEngineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPauseEngineOperationCompleted);
            }
            this.InvokeAsync("PauseEngine", new object[0], this.PauseEngineOperationCompleted, userState);
        }
        
        private void OnPauseEngineOperationCompleted(object arg) {
            if ((this.PauseEngineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PauseEngineCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://arachnode.net/CrawlerService/ResumeEngine", RequestNamespace="http://arachnode.net/CrawlerService", ResponseNamespace="http://arachnode.net/CrawlerService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ResumeEngine() {
            this.Invoke("ResumeEngine", new object[0]);
        }
        
        /// <remarks/>
        public void ResumeEngineAsync() {
            this.ResumeEngineAsync(null);
        }
        
        /// <remarks/>
        public void ResumeEngineAsync(object userState) {
            if ((this.ResumeEngineOperationCompleted == null)) {
                this.ResumeEngineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnResumeEngineOperationCompleted);
            }
            this.InvokeAsync("ResumeEngine", new object[0], this.ResumeEngineOperationCompleted, userState);
        }
        
        private void OnResumeEngineOperationCompleted(object arg) {
            if ((this.ResumeEngineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ResumeEngineCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://arachnode.net/CrawlerService/Reset", RequestNamespace="http://arachnode.net/CrawlerService", ResponseNamespace="http://arachnode.net/CrawlerService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Reset() {
            this.Invoke("Reset", new object[0]);
        }
        
        /// <remarks/>
        public void ResetAsync() {
            this.ResetAsync(null);
        }
        
        /// <remarks/>
        public void ResetAsync(object userState) {
            if ((this.ResetOperationCompleted == null)) {
                this.ResetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnResetOperationCompleted);
            }
            this.InvokeAsync("Reset", new object[0], this.ResetOperationCompleted, userState);
        }
        
        private void OnResetOperationCompleted(object arg) {
            if ((this.ResetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ResetCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://arachnode.net/CrawlerService/GetApplicationSettings", RequestNamespace="http://arachnode.net/CrawlerService", ResponseNamespace="http://arachnode.net/CrawlerService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ApplicationSettings GetApplicationSettings() {
            object[] results = this.Invoke("GetApplicationSettings", new object[0]);
            return ((ApplicationSettings)(results[0]));
        }
        
        /// <remarks/>
        public void GetApplicationSettingsAsync() {
            this.GetApplicationSettingsAsync(null);
        }
        
        /// <remarks/>
        public void GetApplicationSettingsAsync(object userState) {
            if ((this.GetApplicationSettingsOperationCompleted == null)) {
                this.GetApplicationSettingsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetApplicationSettingsOperationCompleted);
            }
            this.InvokeAsync("GetApplicationSettings", new object[0], this.GetApplicationSettingsOperationCompleted, userState);
        }
        
        private void OnGetApplicationSettingsOperationCompleted(object arg) {
            if ((this.GetApplicationSettingsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetApplicationSettingsCompleted(this, new GetApplicationSettingsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://arachnode.net/CrawlerService/GetWebSettings", RequestNamespace="http://arachnode.net/CrawlerService", ResponseNamespace="http://arachnode.net/CrawlerService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WebSettings GetWebSettings() {
            object[] results = this.Invoke("GetWebSettings", new object[0]);
            return ((WebSettings)(results[0]));
        }
        
        /// <remarks/>
        public void GetWebSettingsAsync() {
            this.GetWebSettingsAsync(null);
        }
        
        /// <remarks/>
        public void GetWebSettingsAsync(object userState) {
            if ((this.GetWebSettingsOperationCompleted == null)) {
                this.GetWebSettingsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWebSettingsOperationCompleted);
            }
            this.InvokeAsync("GetWebSettings", new object[0], this.GetWebSettingsOperationCompleted, userState);
        }
        
        private void OnGetWebSettingsOperationCompleted(object arg) {
            if ((this.GetWebSettingsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWebSettingsCompleted(this, new GetWebSettingsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://arachnode.net/CrawlerService/InitializeConfiguration", RequestNamespace="http://arachnode.net/CrawlerService", ResponseNamespace="http://arachnode.net/CrawlerService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InitializeConfiguration() {
            this.Invoke("InitializeConfiguration", new object[0]);
        }
        
        /// <remarks/>
        public void InitializeConfigurationAsync() {
            this.InitializeConfigurationAsync(null);
        }
        
        /// <remarks/>
        public void InitializeConfigurationAsync(object userState) {
            if ((this.InitializeConfigurationOperationCompleted == null)) {
                this.InitializeConfigurationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInitializeConfigurationOperationCompleted);
            }
            this.InvokeAsync("InitializeConfiguration", new object[0], this.InitializeConfigurationOperationCompleted, userState);
        }
        
        private void OnInitializeConfigurationOperationCompleted(object arg) {
            if ((this.InitializeConfigurationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InitializeConfigurationCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://arachnode.net/CrawlerService/GetPerformanceCountersForArachnodeDotNet", RequestNamespace="http://arachnode.net/CrawlerService", ResponseNamespace="http://arachnode.net/CrawlerService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetPerformanceCountersForArachnodeDotNet() {
            object[] results = this.Invoke("GetPerformanceCountersForArachnodeDotNet", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetPerformanceCountersForArachnodeDotNetAsync() {
            this.GetPerformanceCountersForArachnodeDotNetAsync(null);
        }
        
        /// <remarks/>
        public void GetPerformanceCountersForArachnodeDotNetAsync(object userState) {
            if ((this.GetPerformanceCountersForArachnodeDotNetOperationCompleted == null)) {
                this.GetPerformanceCountersForArachnodeDotNetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPerformanceCountersForArachnodeDotNetOperationCompleted);
            }
            this.InvokeAsync("GetPerformanceCountersForArachnodeDotNet", new object[0], this.GetPerformanceCountersForArachnodeDotNetOperationCompleted, userState);
        }
        
        private void OnGetPerformanceCountersForArachnodeDotNetOperationCompleted(object arg) {
            if ((this.GetPerformanceCountersForArachnodeDotNetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPerformanceCountersForArachnodeDotNetCompleted(this, new GetPerformanceCountersForArachnodeDotNetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://arachnode.net/CrawlerService/GetPerformanceCounters", RequestNamespace="http://arachnode.net/CrawlerService", ResponseNamespace="http://arachnode.net/CrawlerService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetPerformanceCounters(string categoryNameStartsWith) {
            object[] results = this.Invoke("GetPerformanceCounters", new object[] {
                        categoryNameStartsWith});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetPerformanceCountersAsync(string categoryNameStartsWith) {
            this.GetPerformanceCountersAsync(categoryNameStartsWith, null);
        }
        
        /// <remarks/>
        public void GetPerformanceCountersAsync(string categoryNameStartsWith, object userState) {
            if ((this.GetPerformanceCountersOperationCompleted == null)) {
                this.GetPerformanceCountersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPerformanceCountersOperationCompleted);
            }
            this.InvokeAsync("GetPerformanceCounters", new object[] {
                        categoryNameStartsWith}, this.GetPerformanceCountersOperationCompleted, userState);
        }
        
        private void OnGetPerformanceCountersOperationCompleted(object arg) {
            if ((this.GetPerformanceCountersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPerformanceCountersCompleted(this, new GetPerformanceCountersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://arachnode.net/CrawlerService/GetAllTableRowCounts", RequestNamespace="http://arachnode.net/CrawlerService", ResponseNamespace="http://arachnode.net/CrawlerService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetAllTableRowCounts() {
            object[] results = this.Invoke("GetAllTableRowCounts", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllTableRowCountsAsync() {
            this.GetAllTableRowCountsAsync(null);
        }
        
        /// <remarks/>
        public void GetAllTableRowCountsAsync(object userState) {
            if ((this.GetAllTableRowCountsOperationCompleted == null)) {
                this.GetAllTableRowCountsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllTableRowCountsOperationCompleted);
            }
            this.InvokeAsync("GetAllTableRowCounts", new object[0], this.GetAllTableRowCountsOperationCompleted, userState);
        }
        
        private void OnGetAllTableRowCountsOperationCompleted(object arg) {
            if ((this.GetAllTableRowCountsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllTableRowCountsCompleted(this, new GetAllTableRowCountsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://arachnode.net/CrawlerService")]
    public partial class ApplicationSettings {
        
        private bool autoThrottleHttpWebRequestsField;
        
        private string acceptField;
        
        private string acceptEncodingField;
        
        private bool allowAutoRedirectField;
        
        private int discoverySlidingExpirationInSecondsField;
        
        private bool insertDisallowedDiscoveriesField;
        
        private bool insertDiscoveriesField;
        
        private bool insertCrawlRequestsField;
        
        private bool insertFileResponseHeadersField;
        
        private bool insertImageResponseHeadersField;
        
        private bool insertWebPageResponseHeadersField;
        
        private bool outputWebExceptionsField;
        
        private int maximumNumberOfAutoRedirectsField;
        
        private bool processDiscoveriesAsynchronouslyField;
        
        private bool setRefererToParentAbsoluteUriField;
        
        private bool processCookiesField;
        
        private bool assignCrawlRequestPrioritiesForFilesField;
        
        private bool assignCrawlRequestPrioritiesForHyperLinksField;
        
        private bool assignCrawlRequestPrioritiesForImagesField;
        
        private bool assignCrawlRequestPrioritiesForWebPagesField;
        
        private bool assignEmailAddressDiscoveriesField;
        
        private bool assignFileAndImageDiscoveriesField;
        
        private bool assignHyperLinkDiscoveriesField;
        
        private bool classifyAbsoluteUrisField;
        
        private string connectionStringField;
        
        private string consoleOutputLogsDirectoryField;
        
        private double crawlRequestTimeoutInMinutesField;
        
        private bool createCrawlRequestsFromDatabaseCrawlRequestsField;
        
        private bool createCrawlRequestsFromDatabaseFilesField;
        
        private bool createCrawlRequestsFromDatabaseHyperLinksField;
        
        private bool createCrawlRequestsFromDatabaseImagesField;
        
        private bool createCrawlRequestsFromDatabaseWebPagesField;
        
        private int desiredMaximumMemoryUsageInMegabytesField;
        
        private string downloadedFilesDirectoryField;
        
        private string downloadedImagesDirectoryField;
        
        private string downloadedWebPagesDirectoryField;
        
        private bool enableConsoleOutputField;
        
        private bool extractFileMetaDataField;
        
        private bool extractImageMetaDataField;
        
        private bool extractWebPageMetaDataField;
        
        private int httpWebRequestRetriesField;
        
        private bool insertDisallowedAbsoluteUriDiscoveriesField;
        
        private bool insertDisallowedAbsoluteUrisField;
        
        private bool insertEmailAddressDiscoveriesField;
        
        private bool insertEmailAddressesField;
        
        private bool insertExceptionsField;
        
        private bool insertFileDiscoveriesField;
        
        private bool insertFileMetaDataField;
        
        private bool insertFilesField;
        
        private bool insertFileSourceField;
        
        private bool insertHyperLinksField;
        
        private bool insertHyperLinkDiscoveriesField;
        
        private bool insertImageDiscoveriesField;
        
        private bool insertImageMetaDataField;
        
        private bool insertImagesField;
        
        private bool insertImageSourceField;
        
        private bool insertWebPageMetaDataField;
        
        private bool insertWebPagesField;
        
        private bool insertWebPageSourceField;
        
        private bool manageDiscoveryStateField;
        
        private int maximumNumberOfCrawlRequestsToCreatePerBatchField;
        
        private int maximumNumberOfCrawlThreadsField;
        
        private int maximumNumberOfHostsAndPrioritiesToSelectField;
        
        private bool outputConsoleToLogsField;
        
        private bool overrideDatabaseConfigurationWithXmlConfigurationField;
        
        private bool saveDiscoveredFilesToDiskField;
        
        private bool saveDiscoveredImagesToDiskField;
        
        private bool saveDiscoveredWebPagesToDiskField;
        
        private string uniqueIdentifierField;
        
        private string userAgentField;
        
        private bool verboseOutputField;
        
        /// <remarks/>
        public bool AutoThrottleHttpWebRequests {
            get {
                return this.autoThrottleHttpWebRequestsField;
            }
            set {
                this.autoThrottleHttpWebRequestsField = value;
            }
        }
        
        /// <remarks/>
        public string Accept {
            get {
                return this.acceptField;
            }
            set {
                this.acceptField = value;
            }
        }
        
        /// <remarks/>
        public string AcceptEncoding {
            get {
                return this.acceptEncodingField;
            }
            set {
                this.acceptEncodingField = value;
            }
        }
        
        /// <remarks/>
        public bool AllowAutoRedirect {
            get {
                return this.allowAutoRedirectField;
            }
            set {
                this.allowAutoRedirectField = value;
            }
        }
        
        /// <remarks/>
        public int DiscoverySlidingExpirationInSeconds {
            get {
                return this.discoverySlidingExpirationInSecondsField;
            }
            set {
                this.discoverySlidingExpirationInSecondsField = value;
            }
        }
        
        /// <remarks/>
        public bool InsertDisallowedDiscoveries {
            get {
                return this.insertDisallowedDiscoveriesField;
            }
            set {
                this.insertDisallowedDiscoveriesField = value;
            }
        }
        
        /// <remarks/>
        public bool InsertDiscoveries {
            get {
                return this.insertDiscoveriesField;
            }
            set {
                this.insertDiscoveriesField = value;
            }
        }
        
        /// <remarks/>
        public bool InsertCrawlRequests {
            get {
                return this.insertCrawlRequestsField;
            }
            set {
                this.insertCrawlRequestsField = value;
            }
        }
        
        /// <remarks/>
        public bool InsertFileResponseHeaders {
            get {
                return this.insertFileResponseHeadersField;
            }
            set {
                this.insertFileResponseHeadersField = value;
            }
        }
        
        /// <remarks/>
        public bool InsertImageResponseHeaders {
            get {
                return this.insertImageResponseHeadersField;
            }
            set {
                this.insertImageResponseHeadersField = value;
            }
        }
        
        /// <remarks/>
        public bool InsertWebPageResponseHeaders {
            get {
                return this.insertWebPageResponseHeadersField;
            }
            set {
                this.insertWebPageResponseHeadersField = value;
            }
        }
        
        /// <remarks/>
        public bool OutputWebExceptions {
            get {
                return this.outputWebExceptionsField;
            }
            set {
                this.outputWebExceptionsField = value;
            }
        }
        
        /// <remarks/>
        public int MaximumNumberOfAutoRedirects {
            get {
                return this.maximumNumberOfAutoRedirectsField;
            }
            set {
                this.maximumNumberOfAutoRedirectsField = value;
            }
        }
        
        /// <remarks/>
        public bool ProcessDiscoveriesAsynchronously {
            get {
                return this.processDiscoveriesAsynchronouslyField;
            }
            set {
                this.processDiscoveriesAsynchronouslyField = value;
            }
        }
        
        /// <remarks/>
        public bool SetRefererToParentAbsoluteUri {
            get {
                return this.setRefererToParentAbsoluteUriField;
            }
            set {
                this.setRefererToParentAbsoluteUriField = value;
            }
        }
        
        /// <remarks/>
        public bool ProcessCookies {
            get {
                return this.processCookiesField;
            }
            set {
                this.processCookiesField = value;
            }
        }
        
        /// <remarks/>
        public bool AssignCrawlRequestPrioritiesForFiles {
            get {
                return this.assignCrawlRequestPrioritiesForFilesField;
            }
            set {
                this.assignCrawlRequestPrioritiesForFilesField = value;
            }
        }
        
        /// <remarks/>
        public bool AssignCrawlRequestPrioritiesForHyperLinks {
            get {
                return this.assignCrawlRequestPrioritiesForHyperLinksField;
            }
            set {
                this.assignCrawlRequestPrioritiesForHyperLinksField = value;
            }
        }
        
        /// <remarks/>
        public bool AssignCrawlRequestPrioritiesForImages {
            get {
                return this.assignCrawlRequestPrioritiesForImagesField;
            }
            set {
                this.assignCrawlRequestPrioritiesForImagesField = value;
            }
        }
        
        /// <remarks/>
        public bool AssignCrawlRequestPrioritiesForWebPages {
            get {
                return this.assignCrawlRequestPrioritiesForWebPagesField;
            }
            set {
                this.assignCrawlRequestPrioritiesForWebPagesField = value;
            }
        }
        
        /// <remarks/>
        public bool AssignEmailAddressDiscoveries {
            get {
                return this.assignEmailAddressDiscoveriesField;
            }
            set {
                this.assignEmailAddressDiscoveriesField = value;
            }
        }
        
        /// <remarks/>
        public bool AssignFileAndImageDiscoveries {
            get {
                return this.assignFileAndImageDiscoveriesField;
            }
            set {
                this.assignFileAndImageDiscoveriesField = value;
            }
        }
        
        /// <remarks/>
        public bool AssignHyperLinkDiscoveries {
            get {
                return this.assignHyperLinkDiscoveriesField;
            }
            set {
                this.assignHyperLinkDiscoveriesField = value;
            }
        }
        
        /// <remarks/>
        public bool ClassifyAbsoluteUris {
            get {
                return this.classifyAbsoluteUrisField;
            }
            set {
                this.classifyAbsoluteUrisField = value;
            }
        }
        
        /// <remarks/>
        public string ConnectionString {
            get {
                return this.connectionStringField;
            }
            set {
                this.connectionStringField = value;
            }
        }
        
        /// <remarks/>
        public string ConsoleOutputLogsDirectory {
            get {
                return this.consoleOutputLogsDirectoryField;
            }
            set {
                this.consoleOutputLogsDirectoryField = value;
            }
        }
        
        /// <remarks/>
        public double CrawlRequestTimeoutInMinutes {
            get {
                return this.crawlRequestTimeoutInMinutesField;
            }
            set {
                this.crawlRequestTimeoutInMinutesField = value;
            }
        }
        
        /// <remarks/>
        public bool CreateCrawlRequestsFromDatabaseCrawlRequests {
            get {
                return this.createCrawlRequestsFromDatabaseCrawlRequestsField;
            }
            set {
                this.createCrawlRequestsFromDatabaseCrawlRequestsField = value;
            }
        }
        
        /// <remarks/>
        public bool CreateCrawlRequestsFromDatabaseFiles {
            get {
                return this.createCrawlRequestsFromDatabaseFilesField;
            }
            set {
                this.createCrawlRequestsFromDatabaseFilesField = value;
            }
        }
        
        /// <remarks/>
        public bool CreateCrawlRequestsFromDatabaseHyperLinks {
            get {
                return this.createCrawlRequestsFromDatabaseHyperLinksField;
            }
            set {
                this.createCrawlRequestsFromDatabaseHyperLinksField = value;
            }
        }
        
        /// <remarks/>
        public bool CreateCrawlRequestsFromDatabaseImages {
            get {
                return this.createCrawlRequestsFromDatabaseImagesField;
            }
            set {
                this.createCrawlRequestsFromDatabaseImagesField = value;
            }
        }
        
        /// <remarks/>
        public bool CreateCrawlRequestsFromDatabaseWebPages {
            get {
                return this.createCrawlRequestsFromDatabaseWebPagesField;
            }
            set {
                this.createCrawlRequestsFromDatabaseWebPagesField = value;
            }
        }
        
        /// <remarks/>
        public int DesiredMaximumMemoryUsageInMegabytes {
            get {
                return this.desiredMaximumMemoryUsageInMegabytesField;
            }
            set {
                this.desiredMaximumMemoryUsageInMegabytesField = value;
            }
        }
        
        /// <remarks/>
        public string DownloadedFilesDirectory {
            get {
                return this.downloadedFilesDirectoryField;
            }
            set {
                this.downloadedFilesDirectoryField = value;
            }
        }
        
        /// <remarks/>
        public string DownloadedImagesDirectory {
            get {
                return this.downloadedImagesDirectoryField;
            }
            set {
                this.downloadedImagesDirectoryField = value;
            }
        }
        
        /// <remarks/>
        public string DownloadedWebPagesDirectory {
            get {
                return this.downloadedWebPagesDirectoryField;
            }
            set {
                this.downloadedWebPagesDirectoryField = value;
            }
        }
        
        /// <remarks/>
        public bool EnableConsoleOutput {
            get {
                return this.enableConsoleOutputField;
            }
            set {
                this.enableConsoleOutputField = value;
            }
        }
        
        /// <remarks/>
        public bool ExtractFileMetaData {
            get {
                return this.extractFileMetaDataField;
            }
            set {
                this.extractFileMetaDataField = value;
            }
        }
        
        /// <remarks/>
        public bool ExtractImageMetaData {
            get {
                return this.extractImageMetaDataField;
            }
            set {
                this.extractImageMetaDataField = value;
            }
        }
        
        /// <remarks/>
        public bool ExtractWebPageMetaData {
            get {
                return this.extractWebPageMetaDataField;
            }
            set {
                this.extractWebPageMetaDataField = value;
            }
        }
        
        /// <remarks/>
        public int HttpWebRequestRetries {
            get {
                return this.httpWebRequestRetriesField;
            }
            set {
                this.httpWebRequestRetriesField = value;
            }
        }
        
        /// <remarks/>
        public bool InsertDisallowedAbsoluteUriDiscoveries {
            get {
                return this.insertDisallowedAbsoluteUriDiscoveriesField;
            }
            set {
                this.insertDisallowedAbsoluteUriDiscoveriesField = value;
            }
        }
        
        /// <remarks/>
        public bool InsertDisallowedAbsoluteUris {
            get {
                return this.insertDisallowedAbsoluteUrisField;
            }
            set {
                this.insertDisallowedAbsoluteUrisField = value;
            }
        }
        
        /// <remarks/>
        public bool InsertEmailAddressDiscoveries {
            get {
                return this.insertEmailAddressDiscoveriesField;
            }
            set {
                this.insertEmailAddressDiscoveriesField = value;
            }
        }
        
        /// <remarks/>
        public bool InsertEmailAddresses {
            get {
                return this.insertEmailAddressesField;
            }
            set {
                this.insertEmailAddressesField = value;
            }
        }
        
        /// <remarks/>
        public bool InsertExceptions {
            get {
                return this.insertExceptionsField;
            }
            set {
                this.insertExceptionsField = value;
            }
        }
        
        /// <remarks/>
        public bool InsertFileDiscoveries {
            get {
                return this.insertFileDiscoveriesField;
            }
            set {
                this.insertFileDiscoveriesField = value;
            }
        }
        
        /// <remarks/>
        public bool InsertFileMetaData {
            get {
                return this.insertFileMetaDataField;
            }
            set {
                this.insertFileMetaDataField = value;
            }
        }
        
        /// <remarks/>
        public bool InsertFiles {
            get {
                return this.insertFilesField;
            }
            set {
                this.insertFilesField = value;
            }
        }
        
        /// <remarks/>
        public bool InsertFileSource {
            get {
                return this.insertFileSourceField;
            }
            set {
                this.insertFileSourceField = value;
            }
        }
        
        /// <remarks/>
        public bool InsertHyperLinks {
            get {
                return this.insertHyperLinksField;
            }
            set {
                this.insertHyperLinksField = value;
            }
        }
        
        /// <remarks/>
        public bool InsertHyperLinkDiscoveries {
            get {
                return this.insertHyperLinkDiscoveriesField;
            }
            set {
                this.insertHyperLinkDiscoveriesField = value;
            }
        }
        
        /// <remarks/>
        public bool InsertImageDiscoveries {
            get {
                return this.insertImageDiscoveriesField;
            }
            set {
                this.insertImageDiscoveriesField = value;
            }
        }
        
        /// <remarks/>
        public bool InsertImageMetaData {
            get {
                return this.insertImageMetaDataField;
            }
            set {
                this.insertImageMetaDataField = value;
            }
        }
        
        /// <remarks/>
        public bool InsertImages {
            get {
                return this.insertImagesField;
            }
            set {
                this.insertImagesField = value;
            }
        }
        
        /// <remarks/>
        public bool InsertImageSource {
            get {
                return this.insertImageSourceField;
            }
            set {
                this.insertImageSourceField = value;
            }
        }
        
        /// <remarks/>
        public bool InsertWebPageMetaData {
            get {
                return this.insertWebPageMetaDataField;
            }
            set {
                this.insertWebPageMetaDataField = value;
            }
        }
        
        /// <remarks/>
        public bool InsertWebPages {
            get {
                return this.insertWebPagesField;
            }
            set {
                this.insertWebPagesField = value;
            }
        }
        
        /// <remarks/>
        public bool InsertWebPageSource {
            get {
                return this.insertWebPageSourceField;
            }
            set {
                this.insertWebPageSourceField = value;
            }
        }
        
        /// <remarks/>
        public bool ManageDiscoveryState {
            get {
                return this.manageDiscoveryStateField;
            }
            set {
                this.manageDiscoveryStateField = value;
            }
        }
        
        /// <remarks/>
        public int MaximumNumberOfCrawlRequestsToCreatePerBatch {
            get {
                return this.maximumNumberOfCrawlRequestsToCreatePerBatchField;
            }
            set {
                this.maximumNumberOfCrawlRequestsToCreatePerBatchField = value;
            }
        }
        
        /// <remarks/>
        public int MaximumNumberOfCrawlThreads {
            get {
                return this.maximumNumberOfCrawlThreadsField;
            }
            set {
                this.maximumNumberOfCrawlThreadsField = value;
            }
        }
        
        /// <remarks/>
        public int MaximumNumberOfHostsAndPrioritiesToSelect {
            get {
                return this.maximumNumberOfHostsAndPrioritiesToSelectField;
            }
            set {
                this.maximumNumberOfHostsAndPrioritiesToSelectField = value;
            }
        }
        
        /// <remarks/>
        public bool OutputConsoleToLogs {
            get {
                return this.outputConsoleToLogsField;
            }
            set {
                this.outputConsoleToLogsField = value;
            }
        }
        
        /// <remarks/>
        public bool OverrideDatabaseConfigurationWithXmlConfiguration {
            get {
                return this.overrideDatabaseConfigurationWithXmlConfigurationField;
            }
            set {
                this.overrideDatabaseConfigurationWithXmlConfigurationField = value;
            }
        }
        
        /// <remarks/>
        public bool SaveDiscoveredFilesToDisk {
            get {
                return this.saveDiscoveredFilesToDiskField;
            }
            set {
                this.saveDiscoveredFilesToDiskField = value;
            }
        }
        
        /// <remarks/>
        public bool SaveDiscoveredImagesToDisk {
            get {
                return this.saveDiscoveredImagesToDiskField;
            }
            set {
                this.saveDiscoveredImagesToDiskField = value;
            }
        }
        
        /// <remarks/>
        public bool SaveDiscoveredWebPagesToDisk {
            get {
                return this.saveDiscoveredWebPagesToDiskField;
            }
            set {
                this.saveDiscoveredWebPagesToDiskField = value;
            }
        }
        
        /// <remarks/>
        public string UniqueIdentifier {
            get {
                return this.uniqueIdentifierField;
            }
            set {
                this.uniqueIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string UserAgent {
            get {
                return this.userAgentField;
            }
            set {
                this.userAgentField = value;
            }
        }
        
        /// <remarks/>
        public bool VerboseOutput {
            get {
                return this.verboseOutputField;
            }
            set {
                this.verboseOutputField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AEngineActionOfArachnodeDAO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ACrawlRuleOfArachnodeDAO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ACrawlActionOfArachnodeDAO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://arachnode.net/CrawlerService")]
    public abstract partial class ABehaviorOfArachnodeDAO {
        
        private string assemblyNameField;
        
        private bool isEnabledField;
        
        private int orderField;
        
        private string typeNameField;
        
        /// <remarks/>
        public string AssemblyName {
            get {
                return this.assemblyNameField;
            }
            set {
                this.assemblyNameField = value;
            }
        }
        
        /// <remarks/>
        public bool IsEnabled {
            get {
                return this.isEnabledField;
            }
            set {
                this.isEnabledField = value;
            }
        }
        
        /// <remarks/>
        public int Order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
            }
        }
        
        /// <remarks/>
        public string TypeName {
            get {
                return this.typeNameField;
            }
            set {
                this.typeNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://arachnode.net/CrawlerService")]
    public abstract partial class AEngineActionOfArachnodeDAO : ABehaviorOfArachnodeDAO {
        
        private EngineActionType engineActionTypeField;
        
        private string settingsField;
        
        /// <remarks/>
        public EngineActionType EngineActionType {
            get {
                return this.engineActionTypeField;
            }
            set {
                this.engineActionTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Settings {
            get {
                return this.settingsField;
            }
            set {
                this.settingsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://arachnode.net/CrawlerService")]
    public enum EngineActionType {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        PreGetCrawlRequests,
        
        /// <remarks/>
        PostGetCrawlRequests,
        
        /// <remarks/>
        PreAndPostGetCrawlRequests,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://arachnode.net/CrawlerService")]
    public abstract partial class ACrawlRuleOfArachnodeDAO : ABehaviorOfArachnodeDAO {
        
        private CrawlRuleType crawlRuleTypeField;
        
        private bool outputIsDisallowedReasonField;
        
        private string settingsField;
        
        /// <remarks/>
        public CrawlRuleType CrawlRuleType {
            get {
                return this.crawlRuleTypeField;
            }
            set {
                this.crawlRuleTypeField = value;
            }
        }
        
        /// <remarks/>
        public bool OutputIsDisallowedReason {
            get {
                return this.outputIsDisallowedReasonField;
            }
            set {
                this.outputIsDisallowedReasonField = value;
            }
        }
        
        /// <remarks/>
        public string Settings {
            get {
                return this.settingsField;
            }
            set {
                this.settingsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://arachnode.net/CrawlerService")]
    public enum CrawlRuleType {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        PreRequest,
        
        /// <remarks/>
        PreGet,
        
        /// <remarks/>
        PostRequest,
        
        /// <remarks/>
        PreAndPostRequest,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://arachnode.net/CrawlerService")]
    public abstract partial class ACrawlActionOfArachnodeDAO : ABehaviorOfArachnodeDAO {
        
        private CrawlActionType crawlActionTypeField;
        
        private string settingsField;
        
        /// <remarks/>
        public CrawlActionType CrawlActionType {
            get {
                return this.crawlActionTypeField;
            }
            set {
                this.crawlActionTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Settings {
            get {
                return this.settingsField;
            }
            set {
                this.settingsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://arachnode.net/CrawlerService")]
    public enum CrawlActionType {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        PreRequest,
        
        /// <remarks/>
        PreGet,
        
        /// <remarks/>
        PostRequest,
        
        /// <remarks/>
        PreAndPostRequest,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://arachnode.net/CrawlerService")]
    public partial class WebSettings {
        
        private int cacheTimeoutInMinutesField;
        
        private string connectionStringField;
        
        private bool createCrawlRequestsForMissingFilesAndImagesField;
        
        private string downloadedFilesVirtualDirectoryField;
        
        private string downloadedImagesVirtualDirectoryField;
        
        private string luceneDotNetIndexDirectoryField;
        
        private int maximumPageTitleLengthField;
        
        private int maximumNumberOfDocumentsToReturnPerSearchField;
        
        private int pageSizeField;
        
        /// <remarks/>
        public int CacheTimeoutInMinutes {
            get {
                return this.cacheTimeoutInMinutesField;
            }
            set {
                this.cacheTimeoutInMinutesField = value;
            }
        }
        
        /// <remarks/>
        public string ConnectionString {
            get {
                return this.connectionStringField;
            }
            set {
                this.connectionStringField = value;
            }
        }
        
        /// <remarks/>
        public bool CreateCrawlRequestsForMissingFilesAndImages {
            get {
                return this.createCrawlRequestsForMissingFilesAndImagesField;
            }
            set {
                this.createCrawlRequestsForMissingFilesAndImagesField = value;
            }
        }
        
        /// <remarks/>
        public string DownloadedFilesVirtualDirectory {
            get {
                return this.downloadedFilesVirtualDirectoryField;
            }
            set {
                this.downloadedFilesVirtualDirectoryField = value;
            }
        }
        
        /// <remarks/>
        public string DownloadedImagesVirtualDirectory {
            get {
                return this.downloadedImagesVirtualDirectoryField;
            }
            set {
                this.downloadedImagesVirtualDirectoryField = value;
            }
        }
        
        /// <remarks/>
        public string LuceneDotNetIndexDirectory {
            get {
                return this.luceneDotNetIndexDirectoryField;
            }
            set {
                this.luceneDotNetIndexDirectoryField = value;
            }
        }
        
        /// <remarks/>
        public int MaximumPageTitleLength {
            get {
                return this.maximumPageTitleLengthField;
            }
            set {
                this.maximumPageTitleLengthField = value;
            }
        }
        
        /// <remarks/>
        public int MaximumNumberOfDocumentsToReturnPerSearch {
            get {
                return this.maximumNumberOfDocumentsToReturnPerSearchField;
            }
            set {
                this.maximumNumberOfDocumentsToReturnPerSearchField = value;
            }
        }
        
        /// <remarks/>
        public int PageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://arachnode.net/CrawlerService")]
    public enum CrawlMode {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        BreadthFirstByPriority,
        
        /// <remarks/>
        DepthFirstByPriority,
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://arachnode.net/CrawlerService")]
    public enum UriClassificationType {
        
        /// <remarks/>
        None = 1,
        
        /// <remarks/>
        Domain = 2,
        
        /// <remarks/>
        Extension = 4,
        
        /// <remarks/>
        FileExtension = 8,
        
        /// <remarks/>
        Host = 16,
        
        /// <remarks/>
        Scheme = 32,
        
        /// <remarks/>
        OriginalDirectoryLevelUp = 64,
        
        /// <remarks/>
        OriginalDirectory = 128,
        
        /// <remarks/>
        OriginalDirectoryLevel = 256,
        
        /// <remarks/>
        OriginalDirectoryLevelDown = 512,
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://arachnode.net/CrawlerService")]
    public enum RenderType {
        
        /// <remarks/>
        None = 1,
        
        /// <remarks/>
        Render = 2,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ConstructorCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void DestructorCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SetApplicationSettingsCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SetWebSettingsCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CrawlCompletedEventHandler(object sender, CrawlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CrawlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CrawlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetCrawlActionsCompletedEventHandler(object sender, GetCrawlActionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCrawlActionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCrawlActionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ACrawlActionOfArachnodeDAO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ACrawlActionOfArachnodeDAO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetCrawlRulesCompletedEventHandler(object sender, GetCrawlRulesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCrawlRulesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCrawlRulesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ACrawlRuleOfArachnodeDAO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ACrawlRuleOfArachnodeDAO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetEngineActionsCompletedEventHandler(object sender, GetEngineActionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEngineActionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEngineActionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AEngineActionOfArachnodeDAO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AEngineActionOfArachnodeDAO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void StartEngineCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void StopEngineCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void PauseEngineCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ResumeEngineCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ResetCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetApplicationSettingsCompletedEventHandler(object sender, GetApplicationSettingsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetApplicationSettingsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetApplicationSettingsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ApplicationSettings Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ApplicationSettings)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetWebSettingsCompletedEventHandler(object sender, GetWebSettingsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWebSettingsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetWebSettingsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WebSettings Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WebSettings)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void InitializeConfigurationCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetPerformanceCountersForArachnodeDotNetCompletedEventHandler(object sender, GetPerformanceCountersForArachnodeDotNetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPerformanceCountersForArachnodeDotNetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPerformanceCountersForArachnodeDotNetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetPerformanceCountersCompletedEventHandler(object sender, GetPerformanceCountersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPerformanceCountersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPerformanceCountersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetAllTableRowCountsCompletedEventHandler(object sender, GetAllTableRowCountsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllTableRowCountsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllTableRowCountsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591